name: "Setup Terraform"
description: "Sets up Terraform and initializes the configuration"
runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.3
        terraform_wrapper: false

    - name: Configure provider
      run: cp .github/provider.tf .
      shell: bash

    - name: Terraform init
      run: terraform init
      shell: bash
