name: test gha

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


  # build:
  #   runs-on: ubuntu-latest
  #   name: Ruby ${{ matrix.ruby }}
  #   strategy:
  #     matrix:
  #       ruby:
  #         - '3.2.0'

  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Set up Ruby
  #     uses: ruby/setup-ruby@v1
  #     with:
  #       ruby-version: ${{ matrix.ruby }}
  #       bundler-cache: true
  #   - name: Run the default task
  #     run: bundle exec rake
