name: Run tests

on:
  pull_request:

permissions:
  id-token: write
  contents: read
env:
  ARM_SKIP_PROVIDER_REGISTRATION: true
  ARM_USE_OIDC: true
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-terraform
      - name: Terraform apply
        run: terraform apply -auto-approve -var "create_vm=true" -var "create_app_service=true" -var "ssh_key=${{ secrets.SSH_PUBLIC_KEY }}"

  app_service_test:
    needs: deploy-infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y libvips sshuttle
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-terraform
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Tests
        env:
          AZURE_ACCOUNT_NAME: ${{secrets.AZURE_ACCOUNT_NAME}}
          AZURE_ACCESS_KEY: ${{secrets.AZURE_ACCESS_KEY}}
          AZURE_PRIVATE_CONTAINER: ${{secrets.AZURE_PRIVATE_CONTAINER}}
          AZURE_PUBLIC_CONTAINER: ${{secrets.AZURE_PUBLIC_CONTAINER}}
          AZURE_PRINCIPAL_ID: ${{secrets.AZURE_PRINCIPAL_ID}}
        run: bundle exec rake test_app_service

  azurevm_test:
    needs: deploy-infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y libvips sshuttle
      - name: SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p /home/runner/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /home/runner/.ssh/id_rsa
          chmod 600 /home/runner/.ssh/id_rsa
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add /home/runner/.ssh/id_rsa
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-terraform
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Tests
        env:
          AZURE_ACCOUNT_NAME: ${{secrets.AZURE_ACCOUNT_NAME}}
          AZURE_ACCESS_KEY: ${{secrets.AZURE_ACCESS_KEY}}
          AZURE_PRIVATE_CONTAINER: ${{secrets.AZURE_PRIVATE_CONTAINER}}
          AZURE_PUBLIC_CONTAINER: ${{secrets.AZURE_PUBLIC_CONTAINER}}
          AZURE_PRINCIPAL_ID: ${{secrets.AZURE_PRINCIPAL_ID}}
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: bundle exec rake test_azure_vm

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y libvips
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Tests
        env:
          AZURE_ACCOUNT_NAME: ${{secrets.AZURE_ACCOUNT_NAME}}
          AZURE_ACCESS_KEY: ${{secrets.AZURE_ACCESS_KEY}}
          AZURE_PRIVATE_CONTAINER: ${{secrets.AZURE_PRIVATE_CONTAINER}}
          AZURE_PUBLIC_CONTAINER: ${{secrets.AZURE_PUBLIC_CONTAINER}}
          AZURE_PRINCIPAL_ID: ${{secrets.AZURE_PRINCIPAL_ID}}
        run: bundle exec rake test
